{% set name = "sqlparse" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlparse-{{ version }}.tar.gz
  sha256: 714d0a4932c059d16189f58ef5411ec2287a4360f17cdd0edd2d09d4c5087c93

build:
  entry_points:
    - sqlformat = sqlparse.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.5

test:
  requires:
    - pip
  commands:
    - pip check
    - sqlformat --help
  imports:
    - sqlparse

about:
  home: https://github.com/andialbrecht/sqlparse
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A non-validating SQL parser module for Python.
  description: |
    sqlparse is a non-validating SQL parser for Python. It provides support
    for parsing, splitting and formatting SQL statements.
  doc_url: https://sqlparse.readthedocs.org
  dev_url: https://github.com/andialbrecht/sqlparse

extra:
  recipe-maintainers:
    - ocefpaf
